name: Ocean Asset Publish

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20' # 20でOKです
          
      - name: Install dependencies
        run: npm install
        
      - name: Run Publish Script
        env:
          OCEAN_PRIVATE_KEY: ${{ secrets.OCEAN_PRIVATE_KEY }}
          RPC_URL: "https://polygon-bor-rpc.publicnode.com"
          GAS_LIMIT: "3000000"
          MAX_FEE: "200000000000"
          PRIO_FEE: "60000000000"
        run: node ocean_recover_ddo.js
